LICENSE.txt
NOTICE.txt
README.md
README.rst

Just some initial setup stuff.
cc @jamesls @mtdowling @rayluo @JordonPhillips

Update README and add license

---

s3transfer/compat.py
s3transfer/download.py
s3transfer/exceptions.py
s3transfer/futures.py
s3transfer/manager.py
s3transfer/subscribers.py
s3transfer/utils.py
tests/__init__.py
tests/functional/test_download.py
tests/integration/__init__.py
tests/integration/test_download.py
tests/unit/test_download.py
tests/unit/test_futures.py
tests/unit/test_upload.py
tests/unit/test_utils.py

Implement download method for TransferManager

---

ACCEPTANCE_TESTS.rst

Added a list of acceptance test that should be addressed in implementation and design of transfer manager. Most of these tests were taken from the CLI and boto3. Currently, an x indicates it has been accounted for and has been tested in some fashion. Hopefully this list will eventually get moved to the docs where we can link to which tests satisfy the acceptance test.

Acceptance tests

---

ACCEPTANCE_TESTS.rst
s3transfer/copies.py
s3transfer/download.py
s3transfer/manager.py
s3transfer/tasks.py
s3transfer/upload.py
s3transfer/utils.py
tests/__init__.py
tests/functional/test_copy.py
tests/functional/test_download.py
tests/functional/test_upload.py
tests/integration/__init__.py
tests/integration/test_copy.py
tests/unit/test_copies.py
tests/unit/test_tasks.py
tests/unit/test_upload.py
tests/unit/test_utils.py

Implement copy method for transfer manager

---

tests/unit/test_upload.py
tests/unit/test_utils.py

Was trying to remove the file before closing the fileobj.

Fix some windows unit tests

---

s3transfer/utils.py
tests/unit/test_utils.py

The idea is to use this as a primitive to control
access to parallel range get downloads to a non
seekable stream.  We need a sliding window to ensure
we limit the amount of memory used to buffer
part data.
In the initial version, I required you to pass in a tag name as well
as a counter (e.g tag='stream-download-foo, counter=1).  This proved
to be problematic because you never actually know what the lowest 
value will be.
cc @kyleknap @JordonPhillips

Add sliding window semaphore

---

requirements-dev.txt
scripts/performance/summarize

The following features were added:
* Ability to summarize more than one file
* Calculate standard deviation
* Print summary in table

Made multiple improvements to summarize script

---

tests/functional/test_upload.py

This fails CI builds and uses 10MB+ of memory.  I added a TODO
about this, but for now we have to resort to patching out this value
to use a min_size of 1.
I used [this commit](https://github.com/boto/s3transfer/blob/7ae5c76c47a225218e09080abc7bb66e3732a1fa/tests/functional/test_upload.py) to put back the previous version of this file before adding in the patch.
cc @kyleknap @JordonPhillips

Put back original test_upload test with small content

---

scripts/performance/summarize

Open csv file in text mode

---

s3transfer/download.py
tests/unit/test_download.py

The io executor and the other primatives that came up with it  were unnecessary for nonranged files as there is only ever one thread working on a particular nonranged download. These were relatively pretty heavy weight so by not using the io executor and writing to the file-like object
immediately upon download improves both speed and memory.

Avoid io executor for nonranged downloads

---

.changes/0.1.9.json
CHANGELOG.rst

Closes https://github.com/boto/s3transfer/issues/75
cc @jamesls @JordonPhillips @stealthycoin

Update changelog for version 0.1.9

---

README.rst
setup.py

Updated ``README`` and classifier to better reflect the status of the project. For the classifier while the literal version is not an alpha, the project is more in the alpha state than the planning state as production level projects rely on ``s3transfer`` but there may be more features added to ``s3transfer`` before it goes GA.
Addresses https://github.com/boto/s3transfer/issues/74
cc @jamesls @JordonPhillips @stealthycoin

Update some info to reflect status of project

---

s3transfer/tasks.py

Yeap. That bothered me enough to create a PR, haha!

quick fix: grammatical error on tasks.py comment

---

.changes/next-release/bugfix-TransferManager-84566.json
s3transfer/manager.py
tests/functional/test_manager.py

Don't mask unicode exceptions

---

s3transfer/constants.py
s3transfer/download.py
s3transfer/manager.py
s3transfer/processpool.py
s3transfer/utils.py
setup.cfg
setup.py
tests/unit/test_processpool.py

These workers will be ran to fulfill GetObject requests to complete a file download

Implement GetObject workers for process pool

---

s3transfer/compat.py
s3transfer/download.py
s3transfer/processpool.py
s3transfer/utils.py
tests/unit/test_processpool.py
tests/unit/test_utils.py

This abstraction submits GetObjectJobs to workers to fulfill the download file job

Implemented process based submitter abstraction

---

s3transfer/futures.py
s3transfer/processpool.py
tests/functional/test_processpool.py
tests/unit/test_processpool.py

There are still some improvements that I would like to add. I put these as TODO comments in the code. I will follow up on these with PR's. If you see anything else that may be an issue let me know. I will either fix it or add a TODO.

Implement future interface for ProcessPoolDownloader

---

s3transfer/compat.py
s3transfer/processpool.py
tests/integration/test_processpool.py
tests/unit/test_compat.py
tests/unit/test_processpool.py

This is specifically for the `ProcessPoolDownloader`.

Add support for fast-fail Ctrl-C

---

s3transfer/processpool.py
tests/functional/test_processpool.py
tests/unit/test_processpool.py

Specifically fix issues around pickleability of arguments passed
into process initializers.

Fix issues with Windows

---

.changes/next-release/feature-ProcessPoolDownloader-94382.json
s3transfer/compat.py
s3transfer/constants.py
s3transfer/download.py
s3transfer/futures.py
s3transfer/manager.py
s3transfer/processpool.py
s3transfer/utils.py
scripts/performance/benchmark
scripts/performance/processpool-download
setup.cfg
setup.py
tests/functional/test_processpool.py
tests/integration/test_processpool.py
tests/unit/test_compat.py
tests/unit/test_processpool.py
tests/unit/test_utils.py

Allows users to speed up the throughput of downloads using processes instead of threads.

Add ProcessPoolDownloader class

---

.changes/next-release/enhancment-ProcessPool-8709.json
s3transfer/constants.py
s3transfer/processpool.py
tests/unit/test_processpool.py

This adds a user agent suffix for the process pool downloader.

Add user agent suffix

---

tests/integration/test_download.py

The test was trying to time when a transfer started.  If it sends
a ctrl-c before or after the test starts, we don't see the keyboard
interrupt.  Previously the test did this by sleeping for some amount
of time.
This commit replaces the sleep with an event.  We use the s3transfer
subscribers to wait until we get a progress callback, then we trigger
an event that causes the main thread to raise the KeyboardInterrupt.

Fix flaky integration test

---

s3transfer/download.py
tests/unit/test_download.py

The first commit cleans up a few linting issues, then https://github.com/boto/s3transfer/commit/70586dcd10af2de7426f78b8e64a1cae3c887973 fixes #120.

Fix unbound local error

---

s3transfer/bandwidth.py

Fix simple typo: unlikley -> unlikely

---

.changes/next-release/bugfix-s3-64211.json
s3transfer/utils.py
tests/unit/test_utils.py

fixes issue https://github.com/boto/botocore/issues/1916

fixing temp filename length to be less than or equal to 255

---

.changes/next-release/enhancement-s3-16441.json
s3transfer/__init__.py
s3transfer/manager.py

Add x-amz-server-side-encryption-context into allowed upload args

Update to add server side encryption context into allowed list

---

.changes/next-release/enhancement-s3-1285.json
s3transfer/constants.py
s3transfer/copies.py
s3transfer/manager.py
s3transfer/upload.py

Add ExpectedBucketOwner

---

requirements-test.txt
scripts/ci/run-tests
tests/unit/test_utils.py

Revert "Move to pytest"

---

tests/functional/test_crt.py

Adding in minor test tweaks to fix issues discovered with CRT during the CLI v2 migration.

Fix testing gaps for CRT

---

s3transfer/futures.py

Last pull request to resolve #199.

Fix param tag

---

.github/workflows/run-crt-test.yml
.github/workflows/run-tests.yml
tox.ini

Move CI to release 3.11 build

---

.pre-commit-config.yaml

Upgrade isort to resolve current action failures. See https://github.com/PyCQA/isort/issues/2083 for details

Fix isort version

---

tests/integration/__init__.py

Update public access settings for integration tests.

Update block public access settings

---

.changes/next-release/bugfix-Subscribers-9032.json

Add changelog for subscribers cache

---

.pre-commit-config.yaml
s3transfer/__init__.py
s3transfer/futures.py
tests/functional/test_copy.py
tests/functional/test_delete.py
tests/unit/test_s3transfer.py

Update to latest versions of pre-commit dependencies.

Pre-commit updates

---

.changes/next-release/bugfix-urllib3-70927.json
s3transfer/__init__.py
s3transfer/utils.py

https://github.com/boto/botocore/issues/3132

Fix retrying incomplete downloads with urllib3 2.x

---

requirements-dev-lock.txt
requirements-dev.txt

Update wheel to the latest release.

Update wheel to latest release

---

s3transfer/subscribers.py

Just a simple spelling mistake fix

Just a simple spelling mistake fix
